### ISSUE TITLE
Where is the ds_config.json

### ISSUE THREAD

**Issue by Juanhui28** [vermouthdky/SimTeG#11]
Thanks for publishing the codebase! But when I tried to use the command in the README to finetune the LM, there is a flag `--deepspeed ds_config.json`. But seems the `ds_config.json` is not provided. Is there anything wrong? @vermouthdky

**Comment by vermouthdky** [comment]
Hi there. Thanks for reaching out. Mine used ds_config is 

{
    "fp16": {
      "enabled": "auto",
      "initial_scale_power": 12
    },
    "bf16":{
      "enabled": "auto"
    },
    "zero_optimization": {
      "stage": 2,
      "reduce_bucket_size": 5e7,
      "allgather_bucket_size": 1.25e9,
      "overlap_comm": true,
      "contiguous_gradients": true
    },
    "zero_allow_untested_optimizer": true,
    "train_micro_batch_size_per_gpu": "auto"
  }

which is a standard second stage deepspeed. Also, if you do want to use deepspeed, you can just comment out this line, and everything should be fine.

**Comment by Juanhui28** [comment]
Thanks!!
